Repository TeamYuml/DecentWorkMobile, pull requests merged in 2018-12, with the labels that each got.

#9 Feature/google sign in with token
  README.md
  app/build.gradle
  app/src/main/java/com/example/teamyuml/decentworkmobile/fragments/SignInGoogle.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/utils/UserAuth.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/views/Login.java
Labels: enhancement

#10 Feature/notice
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/teamyuml/decentworkmobile/views/CustomListView.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/views/NoticeList.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/views/SplashScreen.java
  app/src/main/res/layout/activity_notice_list.xml
  app/src/main/res/layout/notice_list.xml
Labels: enhancement

#12 Feature/notice detail
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/teamyuml/decentworkmobile/views/NoticeDetails.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/views/NoticeList.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/views/Worker.java
  app/src/main/res/layout/activity_notice_details.xml
  app/src/main/res/layout/activity_notice_list.xml
  app/src/main/res/layout/activity_worker.xml
  app/src/main/res/layout/notice_list.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#15 Feature/user panel
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/teamyuml/decentworkmobile/fragments/SignInGoogle.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/utils/UserAuth.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/views/Login.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/views/NoticeList.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/views/UserPanel.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/views/Worker.java
  app/src/main/res/drawable/user_icon.png
  app/src/main/res/layout/activity_notice_list.xml
  app/src/main/res/layout/activity_user_panel.xml
  app/src/main/res/menu/drawer_view.xml
  app/src/main/res/values/strings.xml
Labels: bug, enhancement

#16 Add error handler for volley error reponses
  app/src/main/java/com/example/teamyuml/decentworkmobile/volley/ErrorHandler.java
  app/src/main/res/values/strings.xml
Labels: enhancement

#25 Add swap between login and logout in drawer menu
  app/src/main/java/com/example/teamyuml/decentworkmobile/views/NoticeList.java
  app/src/main/res/menu/drawer_view.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#30 Add functionality for logout item in drawer layout
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/teamyuml/decentworkmobile/utils/UserAuth.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/views/NoticeList.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/views/Worker.java
Labels: enhancement

#32 Change response handler in getWorkers
  app/src/main/java/com/example/teamyuml/decentworkmobile/fragments/ListViewFragment.java
Labels: refactor

#38 Feature/ref worker list
  app/src/main/java/com/example/teamyuml/decentworkmobile/fragments/ProfileDetailsFragment.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/views/NoticeList.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/views/UserPanel.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/views/WorkerDetails.java
  app/src/main/res/layout/activity_user_panel.xml
  app/src/main/res/layout/activity_worker_details.xml
  app/src/main/res/layout/fragment_profiles_details.xml
  app/src/main/res/layout/workers_list.xml
  app/src/main/res/menu/drawer_view.xml
  app/src/main/res/values/strings.xml
Labels: refactor

#14 Feature/login layout
  app/src/main/res/drawable/border_edittext.xml
  app/src/main/res/drawable/google.png
  app/src/main/res/drawable/round_google_button.xml
  app/src/main/res/drawable/title_login.png
  app/src/main/res/font/alegreya_sans_black.ttf
  app/src/main/res/font/alegreya_sans_blackitalic.ttf
  app/src/main/res/font/alegreya_sans_bold.ttf
  app/src/main/res/font/alegreya_sans_bolditalic.ttf
  app/src/main/res/font/alegreya_sans_extrabold.ttf
  app/src/main/res/font/alegreya_sans_extrabolditalic.ttf
  app/src/main/res/font/alegreya_sans_italic.ttf
  app/src/main/res/font/alegreya_sans_light.ttf
  app/src/main/res/font/alegreya_sans_lightitalic.ttf
  app/src/main/res/font/alegreya_sans_medium.ttf
  app/src/main/res/font/alegreya_sans_mediumitalic.ttf
  app/src/main/res/font/alegreya_sans_regular.ttf
  app/src/main/res/font/alegreya_sans_thin.ttf
  app/src/main/res/font/alegreya_sans_thinitalic.ttf
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/google_sign_in.xml
Labels: enhancement

#50 Add possibility to assign to engagment
  app/src/main/java/com/example/teamyuml/decentworkmobile/views/NoticeDetails.java
  app/src/main/res/layout/activity_notice_details.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#52 Add check-assign
  app/src/main/java/com/example/teamyuml/decentworkmobile/views/NoticeDetails.java
Labels: bug, enhancement

#53 Feature/user engagments list
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/teamyuml/decentworkmobile/fragments/ListViewFragment.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/views/NoticeList.java
  app/src/main/res/menu/drawer_view.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#54 Feature/check login for assign
  app/src/main/java/com/example/teamyuml/decentworkmobile/fragments/AssignButtons.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/views/NoticeDetails.java
  app/src/main/res/layout/activity_notice_details.xml
  app/src/main/res/layout/assign_buttons.xml
Labels: enhancement

#56 Add item to drawer and delete spinner
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/teamyuml/decentworkmobile/views/NoticeList.java
  app/src/main/res/drawable/ic_menu.xml
  app/src/main/res/layout/activity_notice_list.xml
  app/src/main/res/menu/drawer_view.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, refactor

#60 Feature/infinite scroll
  app/src/main/java/com/example/teamyuml/decentworkmobile/fragments/ListViewFragment.java
Labels: enhancement

#61 Add url for users with profession, change if state to choose url
  app/src/main/java/com/example/teamyuml/decentworkmobile/fragments/ProfileDetailsFragment.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/views/NoticeList.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/views/UserPanel.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/views/WorkerDetails.java
  app/src/main/res/layout/activity_user_panel.xml
  app/src/main/res/layout/activity_worker_details.xml
Labels: bug

#65 Move adding notice to navigation drawer
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/teamyuml/decentworkmobile/fragments/NoticeForm.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/views/NoticeList.java
  app/src/main/res/layout/activity_engagment_form.xml
  app/src/main/res/layout/notice_form.xml
  app/src/main/res/menu/drawer_view.xml
  app/src/main/res/values/strings.xml
Labels: bug, enhancement

#66 Add intent to my notices after adding notice
  app/src/main/java/com/example/teamyuml/decentworkmobile/fragments/NoticeForm.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/views/NoticeList.java
Labels: enhancement

#68 Add class to return users email, add display users for notices and ad…
  app/src/main/java/com/example/teamyuml/decentworkmobile/model/UserList.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/views/NoticeDetails.java
  app/src/main/res/layout/activity_notice_details.xml
  app/src/main/res/layout/assigned_row_style.xml
Labels: enhancement

#69 Fix infinite scroll for my notice
  app/src/main/java/com/example/teamyuml/decentworkmobile/fragments/ListViewFragment.java
Labels: bug

#71 Feature/improvement urls
  app/src/main/java/com/example/teamyuml/decentworkmobile/fragments/AssignButtons.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/fragments/NoticeForm.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/views/NoticeDetails.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/views/NoticeList.java
Labels: refactor
