Repository TeamYuml/DecentWorkMobile, pull requests merged in 2019-01, with the labels that each got.

#73 Edit fragments for edit notice
  app/src/main/java/com/example/teamyuml/decentworkmobile/fragments/DetailsFragment.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/fragments/NoticeForm.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/views/NoticeDetails.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/views/NoticeList.java
  app/src/main/res/layout/activity_notice_details.xml
  app/src/main/res/layout/notice_details.xml
  app/src/main/res/layout/notice_form.xml
Labels: enhancement, refactor

#74 Feature/new delete notice
  app/src/main/java/com/example/teamyuml/decentworkmobile/fragments/DetailsFragment.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/fragments/NoticeForm.java
  app/src/main/res/layout/notice_details.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#78 Add fragment for professions and cities spinners
  app/src/main/assets/DecentWorkMobile.sqlite
  app/src/main/java/com/example/teamyuml/decentworkmobile/database/DBHelper.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/fragments/NoticeForm.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/fragments/StaticData.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/model/Cities.java
  app/src/main/java/com/example/teamyuml/decentworkmobile/model/Professions.java
  app/src/main/res/layout/cities_profiles.xml
  app/src/main/res/layout/notice_form.xml
Labels: enhancement

#79 Fix add notice show when no loged user
  app/src/main/java/com/example/teamyuml/decentworkmobile/views/NoticeList.java
Labels: bug
